/**
 * NEXUS Telegram Intelligence Engine — Batch v4
 * ─────────────────────────────────────────────────────────────
 * 57 nouveaux canaux analysés, scorés et cartographiés
 *
 * MÉTHODOLOGIE D'ANALYSE :
 * ─────────────────────────
 * Chaque canal est évalué sur 6 dimensions (cf. telegram-intel.ts).
 * Les scores de biais s'appuient sur :
 *   - RAND Corporation "Firehose of Falsehood" (2019)
 *   - Harvard Shorenstein Center — Networked Incitement (Donovan, 2024)
 *   - OSINT for Ukraine — Pro-Russian Telegram analysis (2025)
 *   - OpenMinds Ltd — Russian Disinformation Networks (2024)
 *   - Foreign Policy — Russian Disinfo on Telegram (2022)
 *   - Tactical Media Room — Weaponized OSINT (2022)
 *
 * AVERTISSEMENT LÉGAL/ÉTHIQUE :
 * ─────────────────────────────
 * Certains canaux listés ici (FAR_RIGHT, CONSPIRACY, STATE_MEDIA)
 * sont inclus UNIQUEMENT à des fins d'analyse de narratives et de
 * cartographie de propagation. NEXUS les identifie, les pénalise,
 * et les isole. Ils NE SONT PAS des sources de confiance.
 *
 * FLAGS AUTOMATIQUES :
 *   EXTREMIST_CONTENT     → -40pts + alerte rouge
 *   ANTISEMITIC_CONTENT   → -45pts + alerte rouge
 *   STATE_PROPAGANDA      → -25pts
 *   DISINFORMATION_DOCUMENTED → -30pts
 */

import type { TelegramChannel, ChannelBias, ChannelTier } from './telegram-intel';

// ─── Types étendus pour ce batch ──────────────────────────────
export type ExtendedChannelBias = ChannelBias
  | "FAR_RIGHT"
  | "CONSPIRACY"
  | "STATE_MEDIA"
  | "PRO_RESISTANCE"
  | "DATA_ANALYST"
  | "PRO_PALESTINE"
  | "KURDISH";

export type NarrativeCluster =
  | "WESTERN_ANALYTICS"
  | "RUSSIAN_PROPAGANDA"
  | "RESISTANCE_AXIS"
  | "ISRAEL_PRO"
  | "FAR_RIGHT_EXTREMIST"
  | "CONSPIRACY_ALT"
  | "DATA_VISUALIZATION"
  | "SPANISH_GEOPOLITICS"
  | "NEUTRAL_AGGREGATOR";

export interface ChannelOpposition {
  channelA: string;
  channelB: string;
  type: "DIRECT_NARRATIVE_OPPOSITION" | "IDEOLOGICAL_OPPOSITION" | "FACTUAL_CONTRADICTION";
  intensity: number; // 0-100
  notes: string;
}

export interface ChannelAlliance {
  channels: string[];
  cluster: NarrativeCluster;
  amplificationRate: number; // % messages cross-postés
  notes: string;
}

// ─── 57 NOUVEAUX CANAUX ───────────────────────────────────────

export const NEXUS_CHANNELS_V4: (TelegramChannel & { cluster: NarrativeCluster; extended_bias?: ExtendedChannelBias })[] = [

  // ════════════════════════════════════════════════════════════
  // BLOC 1 — AXE PRO-RÉSISTANCE / IRAN
  // DOCTRINE : Mouvements de résistance, Axe Iran-Hezbollah-Hamas
  // PÉNALITÉ GLOBALE : -18pts (PRO_IRAN_CONFIRMED sur bloc)
  // ════════════════════════════════════════════════════════════

  {
    id: "FotrosResistancee",
    handle: "FotrosResistancee",
    url: "https://t.me/FotrosResistancee",
    name: "Fotros Resistance",
    language: ["fa", "ar", "en"],
    region: ["IR", "IQ", "LB", "YE", "PS"],
    bias: "PRO_IRAN",
    tier: "SECONDARY",
    cluster: "RESISTANCE_AXIS",
    credibilityScore: 48,      // -18 biais PRO_IRAN
    firstMoverScore: 65,       // Fort sur opérations Axe Résistance
    accuracyRate: 58,
    originalContentRate: 60,
    crossVerificationRate: 42,
    editorialLayerScore: 55,
    sourceProximityScore: 75,  // Accès sources iranno-irakiennes
    subscribers: 85000,
    avgPostsPerDay: 15,
    languages: ["fa", "ar", "en"],
    specialties: ["iranian_drones", "irgc_operations", "resistance_axis", "quds_force"],
    knownAffiliations: ["Pro-IRGC / Axe de Résistance — nom du drone iranien Fotros (portée 2000km)"],
    warningFlags: [
      "PRO_IRAN_CONFIRMED",
      "STRATEGIC_NARRATIVE_IRGC",
      "VERIFY_ALL_MILITARY_CLAIMS",
    ],
    medianLeadTimeMinutes: -35,
    forwardedFrom: [],
    forwardedBy: ["QudsNen", "Resistancetoast"],
  },

  {
    id: "QudsNen",
    handle: "QudsNen",
    url: "https://t.me/QudsNen",
    name: "Quds News Network",
    language: ["ar", "en"],
    region: ["PS", "LB", "IQ", "YE", "IR"],
    bias: "PRO_IRAN",
    tier: "SECONDARY",
    cluster: "RESISTANCE_AXIS",
    extended_bias: "PRO_RESISTANCE",
    credibilityScore: 54,
    firstMoverScore: 72,       // Bon sur opérations Gaza/Cisjordanie
    accuracyRate: 62,
    originalContentRate: 70,
    crossVerificationRate: 48,
    editorialLayerScore: 60,
    sourceProximityScore: 80,  // Accès direct milieux pro-Hamas
    subscribers: 420000,
    avgPostsPerDay: 25,
    languages: ["ar", "en"],
    specialties: ["gaza", "west_bank", "hamas", "islamic_jihad", "resistance_operations"],
    knownAffiliations: ["Quds News Network — pro-Hamas/Islamic Jihad"],
    warningFlags: [
      "PRO_IRAN_CONFIRMED",
      "PRO_HAMAS",
      "STRATEGIC_NARRATIVE",
      "VERIFY_CASUALTY_FIGURES",
    ],
    medianLeadTimeMinutes: -40,
    forwardedFrom: ["FotrosResistancee"],
    forwardedBy: ["AlHaqNews", "Resistancetoast"],
  },

  {
    id: "Resistancetoast",
    handle: "Resistancetoast",
    url: "https://t.me/Resistancetoast",
    name: "Resistance Toast",
    language: ["en"],
    region: ["PS", "LB", "IR", "YE"],
    bias: "PRO_IRAN",
    tier: "TERTIARY",
    cluster: "RESISTANCE_AXIS",
    extended_bias: "PRO_RESISTANCE",
    credibilityScore: 40,
    firstMoverScore: 45,
    accuracyRate: 50,
    originalContentRate: 30,
    crossVerificationRate: 35,
    editorialLayerScore: 45,
    sourceProximityScore: 50,
    subscribers: 35000,
    avgPostsPerDay: 40,
    languages: ["en"],
    specialties: ["resistance_memes", "anti_israel", "hamas_ops", "hezbollah"],
    knownAffiliations: ["Pro-Resistance axis meme/aggregation channel"],
    warningFlags: [
      "PRO_IRAN_CONFIRMED",
      "HIGH_AGGREGATION_RATIO",
      "MEME_WARFARE_CONTENT",
      "USE_FOR_SENTIMENT_ANALYSIS_ONLY",
    ],
    medianLeadTimeMinutes: 20,
    forwardedFrom: ["QudsNen", "FotrosResistancee"],
    forwardedBy: [],
  },

  {
    id: "presstv",
    handle: "presstv",
    url: "https://t.me/presstv",
    name: "Press TV",
    language: ["en", "fa"],
    region: ["IR", "PS", "LB", "YE", "IQ"],
    bias: "PRO_IRAN",
    tier: "SECONDARY",
    cluster: "RESISTANCE_AXIS",
    extended_bias: "STATE_MEDIA",
    // État iranien = -25pts STATE_PROPAGANDA sur score brut
    credibilityScore: 38,
    firstMoverScore: 68,
    accuracyRate: 48,          // Faible — mélange faits/narratives d'État
    originalContentRate: 75,
    crossVerificationRate: 35,
    editorialLayerScore: 60,
    sourceProximityScore: 85,  // Accès direct sources IRGC/gouvernement iranien
    subscribers: 1200000,
    avgPostsPerDay: 30,
    languages: ["en", "fa"],
    specialties: ["iran_official", "resistance_axis", "anti_israel", "anti_us_narrative"],
    knownAffiliations: ["MÉDIA D'ÉTAT IRANIEN — financé et dirigé par le gouvernement iranien"],
    warningFlags: [
      "STATE_PROPAGANDA_IRAN",
      "DISINFORMATION_DOCUMENTED",
      "SANCTIONED_ENTITY_US_EU",
      "STRATEGIC_NARRATIVE_ÉTAT",
      "VERIFY_EVERYTHING",
    ],
    medianLeadTimeMinutes: -45,  // Rapide sur événements Iran/Résistance — mais biaisé
    forwardedFrom: [],
    forwardedBy: ["FotrosResistancee", "Resistancetoast"],
  },

  {
    id: "Marwa_OsmanLB",
    handle: "Marwa_OsmanLB",
    url: "https://t.me/Marwa_OsmanLB",
    name: "Marwa Osman",
    language: ["en", "ar"],
    region: ["LB", "SY", "IR"],
    bias: "PRO_IRAN",
    tier: "PRIMARY",
    cluster: "RESISTANCE_AXIS",
    credibilityScore: 50,
    firstMoverScore: 58,
    accuracyRate: 60,
    originalContentRate: 88,  // Contenu très original — commentateur direct
    crossVerificationRate: 42,
    editorialLayerScore: 70,
    sourceProximityScore: 85, // Journaliste libanaise, accès direct milieux Hezbollah
    subscribers: 180000,
    avgPostsPerDay: 12,
    languages: ["en", "ar"],
    specialties: ["hezbollah", "lebanon_politics", "south_lebanon", "iran_perspective"],
    knownAffiliations: ["Commentateur pro-Hezbollah, RT English, Press TV"],
    warningFlags: [
      "PRO_HEZBOLLAH_CONFIRMED",
      "PRO_IRAN_CONFIRMED",
      "PERSONAL_EDITORIAL_BIAS",
      "RT_ASSOCIATED",
    ],
    medianLeadTimeMinutes: -30,
    forwardedFrom: [],
    forwardedBy: ["presstv"],
  },

  {
    id: "AlHaqNews",
    handle: "AlHaqNews",
    url: "https://t.me/AlHaqNews",
    name: "Al-Haq News",
    language: ["ar", "en"],
    region: ["PS", "IL"],
    bias: "PRO_PALESTINE",
    tier: "SECONDARY",
    cluster: "RESISTANCE_AXIS",
    // NOTE: Al-Haq = organisation légitime de droits humains palestiniens
    //       mais listée comme terroriste par Israël depuis 2021 (contesté par l'UE/ONU)
    credibilityScore: 62,
    firstMoverScore: 65,
    accuracyRate: 70,
    originalContentRate: 75,
    crossVerificationRate: 60,
    editorialLayerScore: 65,
    sourceProximityScore: 78,
    subscribers: 95000,
    avgPostsPerDay: 18,
    languages: ["ar", "en"],
    specialties: ["human_rights", "ihl_violations", "west_bank", "siege_documentation"],
    knownAffiliations: ["Al-Haq Palestinian rights org — Ramallah — fondée 1979"],
    warningFlags: [
      "PRO_PALESTINE_STRONG",
      "CONTESTED_DESIGNATION_ISRAEL",
      "CROSS_VERIFY_WITH_UN_OCHA",
    ],
    medianLeadTimeMinutes: -20,
    forwardedFrom: [],
    forwardedBy: [],
  },

  // ════════════════════════════════════════════════════════════
  // BLOC 2 — AXE PRO-ISRAËL
  // ════════════════════════════════════════════════════════════

  {
    id: "DocumentingIsrael",
    handle: "DocumentingIsrael",
    url: "https://t.me/DocumentingIsrael",
    name: "Documenting Israel",
    language: ["en"],
    region: ["IL", "PS"],
    bias: "PRO_PALESTINE",
    tier: "SECONDARY",
    cluster: "NEUTRAL_AGGREGATOR",
    credibilityScore: 68,
    firstMoverScore: 55,
    accuracyRate: 72,
    originalContentRate: 60,
    crossVerificationRate: 65,
    editorialLayerScore: 60,
    sourceProximityScore: 65,
    subscribers: 140000,
    avgPostsPerDay: 20,
    languages: ["en"],
    specialties: ["idf_operations_docs", "settlements", "west_bank", "ihl_documentation"],
    knownAffiliations: ["Documentation critique des actions israéliennes — perspective pro-palestinienne"],
    warningFlags: ["PRO_PALESTINE_EDITORIAL", "CROSS_VERIFY_DATES_CONTEXT"],
    medianLeadTimeMinutes: -10,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "JewsIsrael",
    handle: "JewsIsrael",
    url: "https://t.me/JewsIsrael",
    name: "Jews Israel",
    language: ["en", "he"],
    region: ["IL", "PS"],
    bias: "PRO_ISRAEL",
    tier: "SECONDARY",
    cluster: "ISRAEL_PRO",
    credibilityScore: 58,
    firstMoverScore: 50,
    accuracyRate: 65,
    originalContentRate: 45,
    crossVerificationRate: 55,
    editorialLayerScore: 55,
    sourceProximityScore: 65,
    subscribers: 75000,
    avgPostsPerDay: 25,
    languages: ["en", "he"],
    specialties: ["israel_security", "idf", "anti_semitism_tracking", "jewish_diaspora"],
    knownAffiliations: ["Communauté juive pro-Israël"],
    warningFlags: ["PRO_ISRAEL_BIAS", "AGGREGATOR_UNVERIFIED_SPEED"],
    medianLeadTimeMinutes: 5,
    forwardedFrom: ["idfofficial"],
    forwardedBy: [],
  },

  {
    id: "what_where_when_en",
    handle: "what_where_when_en",
    url: "https://t.me/what_where_when_en",
    name: "What Where When",
    language: ["en"],
    region: ["GLOBAL"],
    bias: "AGGREGATOR",
    tier: "SECONDARY",
    cluster: "NEUTRAL_AGGREGATOR",
    credibilityScore: 65,
    firstMoverScore: 68,
    accuracyRate: 68,
    originalContentRate: 30,
    crossVerificationRate: 60,
    editorialLayerScore: 40,
    sourceProximityScore: 30,
    subscribers: 180000,
    avgPostsPerDay: 45,
    languages: ["en"],
    specialties: ["global_news", "fast_aggregation", "breaking_news"],
    knownAffiliations: ["Agrégateur international — anglophone"],
    warningFlags: ["SPEED_OVER_ACCURACY_RISK", "HIGH_AGGREGATION_RATIO"],
    medianLeadTimeMinutes: -15,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "Israel_Realtime_Digest",
    handle: "Israel_Realtime_Digest",
    url: "https://t.me/Israel_Realtime_Digest",
    name: "Israel Realtime Digest",
    language: ["en"],
    region: ["IL", "PS", "LB"],
    bias: "PRO_ISRAEL",
    tier: "SECONDARY",
    cluster: "ISRAEL_PRO",
    credibilityScore: 62,
    firstMoverScore: 60,
    accuracyRate: 67,
    originalContentRate: 35,
    crossVerificationRate: 58,
    editorialLayerScore: 45,
    sourceProximityScore: 65,
    subscribers: 120000,
    avgPostsPerDay: 35,
    languages: ["en"],
    specialties: ["israel_news", "hamas", "hezbollah", "idf_operations"],
    knownAffiliations: ["Pro-Israel digest/agrégateur"],
    warningFlags: ["PRO_ISRAEL_BIAS", "AGGREGATOR_HIGH_VOLUME"],
    medianLeadTimeMinutes: -5,
    forwardedFrom: ["idfofficial", "JewishNews24"],
    forwardedBy: [],
  },

  {
    id: "idostandwithisrael",
    handle: "idostandwithisrael",
    url: "https://t.me/idostandwithisrael",
    name: "I Do Stand With Israel",
    language: ["en"],
    region: ["IL"],
    bias: "PRO_ISRAEL",
    tier: "TERTIARY",
    cluster: "ISRAEL_PRO",
    // Canal d'activisme explicite — pas source OSINT
    credibilityScore: 48,
    firstMoverScore: 35,
    accuracyRate: 58,
    originalContentRate: 25,
    crossVerificationRate: 45,
    editorialLayerScore: 35,
    sourceProximityScore: 50,
    subscribers: 60000,
    avgPostsPerDay: 30,
    languages: ["en"],
    specialties: ["israel_advocacy", "anti_hamas", "jewish_values"],
    knownAffiliations: ["Activisme pro-Israël — non-journalistique"],
    warningFlags: ["ADVOCACY_NOT_JOURNALISM", "USE_FOR_SENTIMENT_ONLY", "HIGH_AGGREGATION_RATIO"],
    medianLeadTimeMinutes: 25,
    forwardedFrom: ["idfofficial"],
    forwardedBy: [],
  },

  {
    id: "JewishNews24",
    handle: "JewishNews24",
    url: "https://t.me/JewishNews24",
    name: "Jewish News 24",
    language: ["en"],
    region: ["IL", "GLOBAL"],
    bias: "PRO_ISRAEL",
    tier: "SECONDARY",
    cluster: "ISRAEL_PRO",
    credibilityScore: 63,
    firstMoverScore: 58,
    accuracyRate: 68,
    originalContentRate: 40,
    crossVerificationRate: 60,
    editorialLayerScore: 50,
    sourceProximityScore: 60,
    subscribers: 145000,
    avgPostsPerDay: 28,
    languages: ["en"],
    specialties: ["jewish_world_news", "antisemitism", "israel_security", "diaspora"],
    knownAffiliations: ["Médias communauté juive — perspective pro-Israël"],
    warningFlags: ["PRO_ISRAEL_EDITORIAL"],
    medianLeadTimeMinutes: 10,
    forwardedFrom: [],
    forwardedBy: ["Israel_Realtime_Digest"],
  },

  {
    id: "allisrael",
    handle: "allisrael",
    url: "https://t.me/allisrael",
    name: "All Israel News",
    language: ["en"],
    region: ["IL", "PS"],
    bias: "PRO_ISRAEL",
    tier: "SECONDARY",
    cluster: "ISRAEL_PRO",
    credibilityScore: 64,
    firstMoverScore: 62,
    accuracyRate: 70,
    originalContentRate: 50,
    crossVerificationRate: 62,
    editorialLayerScore: 55,
    sourceProximityScore: 68,
    subscribers: 200000,
    avgPostsPerDay: 22,
    languages: ["en"],
    specialties: ["israel_domestic", "knesset", "security_cabinet", "settlements"],
    knownAffiliations: ["All Israel News — fondé par Joel Rosenberg"],
    warningFlags: ["PRO_ISRAEL_EVANGELICAL_PERSPECTIVE"],
    medianLeadTimeMinutes: -8,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "JewishBreakingNewsTelegram",
    handle: "JewishBreakingNewsTelegram",
    url: "https://t.me/JewishBreakingNewsTelegram",
    name: "Jewish Breaking News",
    language: ["en"],
    region: ["IL", "GLOBAL"],
    bias: "PRO_ISRAEL",
    tier: "TERTIARY",
    cluster: "ISRAEL_PRO",
    credibilityScore: 58,
    firstMoverScore: 55,
    accuracyRate: 63,
    originalContentRate: 25,
    crossVerificationRate: 52,
    editorialLayerScore: 35,
    sourceProximityScore: 55,
    subscribers: 90000,
    avgPostsPerDay: 40,
    languages: ["en"],
    specialties: ["jewish_community", "israel_news", "antisemitism_incidents"],
    knownAffiliations: ["Agrégateur communauté juive"],
    warningFlags: ["HIGH_VOLUME_LOW_VERIFICATION", "PRO_ISRAEL_BIAS"],
    medianLeadTimeMinutes: 15,
    forwardedFrom: ["JewishNews24", "idfofficial"],
    forwardedBy: [],
  },

  // ════════════════════════════════════════════════════════════
  // BLOC 3 — AXE PRO-RUSSIE / SLAVISME
  // PÉNALITÉ : -20pts (PRO_RUSSIA_CONFIRMED documenté)
  // Sources recherchées: OSINT for Ukraine, OpenMinds, Foreign Policy 2022
  // ════════════════════════════════════════════════════════════

  {
    id: "Slavyangrad",
    handle: "Slavyangrad",
    url: "https://t.me/Slavyangrad",
    name: "Slavyangrad",
    language: ["en", "es", "ru"],
    region: ["UA", "RU", "BY"],
    bias: "PRO_RUSSIA",
    tier: "SECONDARY",
    cluster: "RUSSIAN_PROPAGANDA",
    // DOCUMENTÉ: OSINT for Ukraine, OpenMinds Ltd 2024, Foreign Policy 2022
    credibilityScore: 42,
    firstMoverScore: 65,       // Rapide sur position russe — mais biaisé
    accuracyRate: 52,
    originalContentRate: 55,
    crossVerificationRate: 38,
    editorialLayerScore: 65,   // Bonne analyse mais pro-russe systématique
    sourceProximityScore: 70,  // Accès sources russes
    subscribers: 380000,
    avgPostsPerDay: 25,
    languages: ["en", "es", "ru"],
    specialties: ["ukraine_war_russian_pov", "frontline_russia", "nato_criticism", "slavic_unity"],
    knownAffiliations: [
      "DOCUMENTÉ comme conduit de propagande russe par OSINT for Ukraine (2025)",
      "Référencé dans réseau pro-russe par OpenMinds Ltd (2024)",
      "Foreign Policy: 'laundering Kremlin information operations' (2022)"
    ],
    warningFlags: [
      "PRO_RUSSIA_CONFIRMED",
      "DISINFORMATION_DOCUMENTED",
      "VERIFY_ALL_MILITARY_CLAIMS",
      "PART_OF_KREMLIN_DISINFO_NETWORK",
    ],
    medianLeadTimeMinutes: -30, // Lead réel sur opérations russes mais biaisé
    forwardedFrom: [],
    forwardedBy: ["FiorellaInMoscow", "Irinamar_Z"],
  },

  {
    id: "FiorellaInMoscow",
    handle: "FiorellaInMoscow",
    url: "https://t.me/FiorellaInMoscow",
    name: "Fiorella In Moscow",
    language: ["en"],
    region: ["RU", "UA", "GLOBAL"],
    bias: "PRO_RUSSIA",
    tier: "SECONDARY",
    cluster: "RUSSIAN_PROPAGANDA",
    // DOCUMENTÉ: OpenMinds 2024 — "Russian propaganda conduit"
    // Réseau: Slavyangrad → FiorellaInMoscow → Taylor Hudak → canaux US
    credibilityScore: 38,
    firstMoverScore: 55,
    accuracyRate: 45,
    originalContentRate: 75,   // Contenu original — commentateur direct depuis Moscou
    crossVerificationRate: 30,
    editorialLayerScore: 60,
    sourceProximityScore: 80,  // Physiquement à Moscou
    subscribers: 125000,
    avgPostsPerDay: 15,
    languages: ["en"],
    specialties: ["russia_narrative", "ukraine_war_russia_pov", "nato_opposition", "multipolar_world"],
    knownAffiliations: [
      "Fiorella Isabel — journaliste américaine basée à Moscou",
      "DOCUMENTÉ: conduit de propagande russe par OpenMinds Ltd (2024)",
      "Réseau: Slavyangrad → FiorellaInMoscow → Taylor Hudak → canaux élections US"
    ],
    warningFlags: [
      "PRO_RUSSIA_CONFIRMED",
      "RUSSIAN_PROPAGANDA_NETWORK",
      "DISINFORMATION_DOCUMENTED_OPENMINDS",
    ],
    medianLeadTimeMinutes: -20,
    forwardedFrom: ["Slavyangrad", "sonar_21"],
    forwardedBy: [],
  },

  {
    id: "Irinamar_Z",
    handle: "Irinamar_Z",
    url: "https://t.me/Irinamar_Z",
    name: "Irina Markovskaya Z",
    language: ["ru", "en"],
    region: ["UA", "RU"],
    bias: "PRO_RUSSIA",
    tier: "TERTIARY",
    cluster: "RUSSIAN_PROPAGANDA",
    // Le "Z" dans le nom = endorsement opération militaire russe
    credibilityScore: 42,
    firstMoverScore: 60,
    accuracyRate: 50,
    originalContentRate: 60,
    crossVerificationRate: 35,
    editorialLayerScore: 50,
    sourceProximityScore: 72,
    subscribers: 95000,
    avgPostsPerDay: 20,
    languages: ["ru", "en"],
    specialties: ["frontline_russia", "ukraine_war_z_perspective", "russian_military"],
    knownAffiliations: ["Pro-Russie — Z = symbole d'approbation opération militaire"],
    warningFlags: [
      "PRO_RUSSIA_Z_SYMBOL",
      "VERIFY_ALL_FRONTLINE_CLAIMS",
      "ONE_SIDED_COVERAGE",
    ],
    medianLeadTimeMinutes: -25,
    forwardedFrom: ["Slavyangrad"],
    forwardedBy: [],
  },

  {
    id: "tass_es",
    handle: "tass_es",
    url: "https://t.me/tass_es",
    name: "TASS en Español",
    language: ["es"],
    region: ["RU", "GLOBAL"],
    bias: "PRO_RUSSIA",
    tier: "SECONDARY",
    cluster: "RUSSIAN_PROPAGANDA",
    extended_bias: "STATE_MEDIA",
    // TASS = Agence de presse d'État russe (Telegrafnoye Agentstvo Sovetskogo Soyuza)
    credibilityScore: 38,
    firstMoverScore: 72,       // Rapide sur positions officielles russes
    accuracyRate: 55,          // Précis sur faits bruts russes, biaisé sur contexte
    originalContentRate: 80,
    crossVerificationRate: 32,
    editorialLayerScore: 50,
    sourceProximityScore: 90,  // Source directe du gouvernement russe
    subscribers: 580000,
    avgPostsPerDay: 40,
    languages: ["es"],
    specialties: ["russia_official", "ukraine_war_russian_narrative", "kremlin_positions"],
    knownAffiliations: ["TASS — Agence d'état russe. Opère depuis 1902. Version hispanophone."],
    warningFlags: [
      "STATE_PROPAGANDA_RUSSIA",
      "SANCTIONED_ENTITY_EU_UK_US",
      "OFFICIAL_KREMLIN_NARRATIVE",
      "VERIFY_ALL_CONFLICT_CLAIMS",
    ],
    medianLeadTimeMinutes: -50, // Premier sur positions officielles russes (source directe)
    forwardedFrom: [],
    forwardedBy: ["Slavyangrad", "FiorellaInMoscow"],
  },

  {
    id: "VanessaBeeley",
    handle: "VanessaBeeley",
    url: "https://t.me/VanessaBeeley",
    name: "Vanessa Beeley",
    language: ["en"],
    region: ["SY", "RU", "IL"],
    bias: "PRO_RUSSIA",
    tier: "PRIMARY",
    cluster: "RUSSIAN_PROPAGANDA",
    // Journaliste britannique — controversée, pro-Assad/Russie documenté
    // Multiplex de RT, travaux cités par sources pro-Kremlin
    credibilityScore: 40,
    firstMoverScore: 62,
    accuracyRate: 48,
    originalContentRate: 90,  // Contenu très original — journaliste terrain
    crossVerificationRate: 35,
    editorialLayerScore: 70,
    sourceProximityScore: 78, // Accès direct zone syrienne
    subscribers: 95000,
    avgPostsPerDay: 8,
    languages: ["en"],
    specialties: ["syria_pro_assad", "white_helmets_opposition", "nato_criticism", "russia_narrative"],
    knownAffiliations: [
      "RT (Russia Today) associé",
      "Contradictions documentées sur chimique Douma 2018 (vs OPCW)",
      "Citée abondamment par médias pro-Kremlin"
    ],
    warningFlags: [
      "PRO_RUSSIA_CONFIRMED",
      "PRO_RUSSIA_DOCUMENTED",
      "CONTRADICTIONS_OPCW_DOCUMENTED",
      "VERIFY_ALL_CHEMICAL_WEAPON_CLAIMS",
    ],
    medianLeadTimeMinutes: -15,
    forwardedFrom: [],
    forwardedBy: ["FiorellaInMoscow"],
  },

  {
    id: "sonar_21",
    handle: "sonar_21",
    url: "https://t.me/sonar_21",
    name: "Sonar 21",
    language: ["en"],
    region: ["UA", "RU", "GLOBAL"],
    bias: "PRO_RUSSIA",
    tier: "SECONDARY",
    cluster: "RUSSIAN_PROPAGANDA",
    // Sonar21.com — analyse géopolitique pro-russe, multipolaire
    credibilityScore: 48,
    firstMoverScore: 58,
    accuracyRate: 55,
    originalContentRate: 72,
    crossVerificationRate: 42,
    editorialLayerScore: 72,  // Bonne qualité analytique — mais biais fort
    sourceProximityScore: 62,
    subscribers: 145000,
    avgPostsPerDay: 12,
    languages: ["en"],
    specialties: ["geopolitics_multipolar", "russia_ukraine_analysis", "nato_criticism", "energy_geopolitics"],
    knownAffiliations: ["Sonar21.com — pro-russe / multipolaire — cité dans réseaux Kremlin"],
    warningFlags: [
      "PRO_RUSSIA_CONFIRMED",
      "MULTIPOLAR_STRATEGIC_NARRATIVE",
      "CROSS_VERIFY_WITH_ISW",
    ],
    medianLeadTimeMinutes: -25,
    forwardedFrom: ["Slavyangrad"],
    forwardedBy: ["FiorellaInMoscow"],
  },

  // ════════════════════════════════════════════════════════════
  // BLOC 4 — ANALYTIQUES OCCIDENTAUX / NEUTRES
  // Les plus utilisables comme sources dans NEXUS
  // ════════════════════════════════════════════════════════════

  {
    id: "iswnews_en",
    handle: "iswnews_en",
    url: "https://t.me/iswnews_en",
    name: "ISW — Institute for the Study of War",
    language: ["en"],
    region: ["UA", "RU", "IR", "SY", "IQ"],
    bias: "ANALYST",
    tier: "SECONDARY",
    cluster: "WESTERN_ANALYTICS",
    // ISW = référence analytique majeure — biais pro-Ukraine assumé mais méthodologie rigoureuse
    credibilityScore: 83,
    firstMoverScore: 60,       // Pas le plus rapide — mais le plus rigoureux
    accuracyRate: 88,
    originalContentRate: 85,
    crossVerificationRate: 90,
    editorialLayerScore: 95,   // Excellence analytique
    sourceProximityScore: 55,
    subscribers: 520000,
    avgPostsPerDay: 8,
    languages: ["en"],
    specialties: ["ukraine_war_analysis", "russia_oob", "iran_military", "threat_assessment"],
    knownAffiliations: ["Institute for the Study of War — Washington DC — think-tank néocon"],
    warningFlags: ["PRO_UKRAINE_FRAMING", "VERIFY_VIA_TERRAIN_SOURCES"],
    medianLeadTimeMinutes: 30,  // Publie des analyses — pas du breaking news
    forwardedFrom: [],
    forwardedBy: ["ClashReport", "MilitantWire"],
  },

  {
    id: "ClashReport",
    handle: "ClashReport",
    url: "https://t.me/ClashReport",
    name: "Clash Report",
    language: ["en", "tr", "fr", "ar"],
    region: ["GLOBAL"],
    bias: "AGGREGATOR",
    tier: "SECONDARY",
    cluster: "NEUTRAL_AGGREGATOR",
    // Origine turque — multilingue (EN/TR/FR/AR) — bonne neutralité opérationnelle
    credibilityScore: 74,
    firstMoverScore: 75,
    accuracyRate: 78,
    originalContentRate: 45,
    crossVerificationRate: 72,
    editorialLayerScore: 60,
    sourceProximityScore: 50,
    subscribers: 680000,
    avgPostsPerDay: 35,
    languages: ["en", "tr", "fr", "ar"],
    specialties: ["global_conflict", "breaking_news", "middle_east", "ukraine"],
    knownAffiliations: ["Origine turque — multilingue — bonne neutralité relative"],
    warningFlags: ["AGGREGATOR_SPEED_RISK", "CROSS_VERIFY_BEFORE_USE"],
    medianLeadTimeMinutes: -20,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "MilitantWire",
    handle: "MilitantWire",
    url: "https://t.me/MilitantWire",
    name: "Militant Wire",
    language: ["en"],
    region: ["SY", "IQ", "UA", "AF", "GLOBAL"],
    bias: "ANALYST",
    tier: "SECONDARY",
    cluster: "WESTERN_ANALYTICS",
    credibilityScore: 74,
    firstMoverScore: 70,
    accuracyRate: 79,
    originalContentRate: 65,
    crossVerificationRate: 75,
    editorialLayerScore: 75,
    sourceProximityScore: 60,
    subscribers: 190000,
    avgPostsPerDay: 15,
    languages: ["en"],
    specialties: ["militant_groups", "isis_tracking", "syria_ops", "armed_groups_oob"],
    knownAffiliations: ["Analytique occidental — fort sur groupes armés non-étatiques"],
    warningFlags: ["PRO_WEST_LENS_POSSIBLE"],
    medianLeadTimeMinutes: -25,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "thewarreporter",
    handle: "thewarreporter",
    url: "https://t.me/thewarreporter",
    name: "The War Reporter",
    language: ["en"],
    region: ["GLOBAL"],
    bias: "AGGREGATOR",
    tier: "SECONDARY",
    cluster: "NEUTRAL_AGGREGATOR",
    credibilityScore: 66,
    firstMoverScore: 65,
    accuracyRate: 70,
    originalContentRate: 38,
    crossVerificationRate: 63,
    editorialLayerScore: 52,
    sourceProximityScore: 40,
    subscribers: 245000,
    avgPostsPerDay: 30,
    languages: ["en"],
    specialties: ["global_war_news", "conflict_updates", "breaking"],
    knownAffiliations: ["Agrégateur anglophone — identité inconnue"],
    warningFlags: ["IDENTITY_UNKNOWN", "AGGREGATION_HIGH"],
    medianLeadTimeMinutes: -10,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "WorldWarNowTele",
    handle: "WorldWarNowTele",
    url: "https://t.me/WorldWarNowTele",
    name: "World War Now",
    language: ["en"],
    region: ["GLOBAL"],
    bias: "AGGREGATOR",
    tier: "TERTIARY",
    cluster: "NEUTRAL_AGGREGATOR",
    credibilityScore: 60,
    firstMoverScore: 62,
    accuracyRate: 65,
    originalContentRate: 20,
    crossVerificationRate: 55,
    editorialLayerScore: 35,
    sourceProximityScore: 25,
    subscribers: 185000,
    avgPostsPerDay: 50,
    languages: ["en"],
    specialties: ["global_conflict", "aggregation", "breaking_headlines"],
    knownAffiliations: ["Agrégateur haut volume — low-quality"],
    warningFlags: ["HIGH_VOLUME_LOW_QUALITY", "USE_FOR_LEADS_ONLY", "NO_VERIFICATION"],
    medianLeadTimeMinutes: 0,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "disclosetv",
    handle: "disclosetv",
    url: "https://t.me/disclosetv",
    name: "disclose.tv",
    language: ["en"],
    region: ["GLOBAL"],
    bias: "AGGREGATOR",
    tier: "TERTIARY",
    cluster: "CONSPIRACY_ALT",
    // disclose.tv = mélange breaking news + contenu alternatif/conspirationniste
    credibilityScore: 52,
    firstMoverScore: 68,       // Rapide mais souvent non-vérifié
    accuracyRate: 58,
    originalContentRate: 35,
    crossVerificationRate: 42,
    editorialLayerScore: 30,
    sourceProximityScore: 25,
    subscribers: 1200000,
    avgPostsPerDay: 60,
    languages: ["en"],
    specialties: ["breaking_news_fast", "alternative_narratives", "social_unrest"],
    knownAffiliations: ["Agrégateur alt-media — mélange news réelles + contenu alternatif"],
    warningFlags: [
      "HIGH_MISINFO_RATE_DOCUMENTED",
      "CONSPIRATORIAL_CONTENT_MIXED",
      "VERIFY_ALL_CLAIMS",
      "USE_FOR_LEADS_ONLY_HIGH_RISK",
    ],
    medianLeadTimeMinutes: -25,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "tg301military",
    handle: "tg301military",
    url: "https://t.me/tg301military",
    name: "301 Military",
    language: ["en"],
    region: ["GLOBAL"],
    bias: "AGGREGATOR",
    tier: "SECONDARY",
    cluster: "NEUTRAL_AGGREGATOR",
    credibilityScore: 63,
    firstMoverScore: 60,
    accuracyRate: 67,
    originalContentRate: 40,
    crossVerificationRate: 58,
    editorialLayerScore: 48,
    sourceProximityScore: 42,
    subscribers: 220000,
    avgPostsPerDay: 30,
    languages: ["en"],
    specialties: ["military_equipment", "weapons_systems", "defense_tech", "global_military"],
    knownAffiliations: ["Agrégateur militaire anglophone"],
    warningFlags: ["AGGREGATION_UNVERIFIED"],
    medianLeadTimeMinutes: -5,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "war_noir",
    handle: "war_noir",
    url: "https://t.me/war_noir",
    name: "War Noir",
    language: ["en"],
    region: ["GLOBAL"],
    bias: "AGGREGATOR",
    tier: "TERTIARY",
    cluster: "NEUTRAL_AGGREGATOR",
    credibilityScore: 45,
    firstMoverScore: 50,
    accuracyRate: 52,
    originalContentRate: 15,
    crossVerificationRate: 38,
    editorialLayerScore: 20,
    sourceProximityScore: 20,
    subscribers: 95000,
    avgPostsPerDay: 55,
    languages: ["en"],
    specialties: ["war_footage", "raw_combat_video", "drone_strikes_footage"],
    knownAffiliations: ["Canal de footage brut — pas de vérification"],
    warningFlags: [
      "NO_VERIFICATION",
      "GRAPHIC_CONTENT",
      "WATERMARKS_ATTRIBUTION_LOST",
      "USE_FOR_LEADS_ONLY",
    ],
    medianLeadTimeMinutes: 10,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "armapedia",
    handle: "armapedia",
    url: "https://t.me/armapedia",
    name: "Armapedia",
    language: ["en"],
    region: ["GLOBAL"],
    bias: "ANALYST",
    tier: "SECONDARY",
    cluster: "WESTERN_ANALYTICS",
    // Encyclopédie des armements — excellente référence technique
    credibilityScore: 72,
    firstMoverScore: 35,
    accuracyRate: 82,
    originalContentRate: 75,
    crossVerificationRate: 78,
    editorialLayerScore: 80,
    sourceProximityScore: 55,
    subscribers: 180000,
    avgPostsPerDay: 6,
    languages: ["en"],
    specialties: ["weapons_systems", "military_tech", "munitions_identification", "oob_analysis"],
    knownAffiliations: ["Référence technique armements — non-partisan"],
    warningFlags: [],
    medianLeadTimeMinutes: 60, // Analyse post-événement — pas breaking news
    forwardedFrom: [],
    forwardedBy: ["MilitantWire"],
  },

  {
    id: "KurdishFrontNews",
    handle: "KurdishFrontNews",
    url: "https://t.me/KurdishFrontNews",
    name: "Kurdish Front News",
    language: ["en", "ku", "ar"],
    region: ["IQ", "SY", "TR", "IR"],
    bias: "FIELD_REPORTER",
    tier: "PRIMARY",
    cluster: "NEUTRAL_AGGREGATOR",
    extended_bias: "KURDISH",
    credibilityScore: 68,
    firstMoverScore: 72,
    accuracyRate: 74,
    originalContentRate: 75,
    crossVerificationRate: 68,
    editorialLayerScore: 68,
    sourceProximityScore: 82,
    subscribers: 135000,
    avgPostsPerDay: 18,
    languages: ["en", "ku", "ar"],
    specialties: ["kurdistan", "peshmerga", "pkk_turkey", "rojava_sdf", "iraq_syria_kurdish"],
    knownAffiliations: ["Presse kurde — perspective SDC/Peshmerga selon zones"],
    warningFlags: ["KURDISH_PERSPECTIVE_LENS", "CROSS_VERIFY_TURKEY_CLAIMS"],
    medianLeadTimeMinutes: -35,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "DefenseBlog",
    handle: "DefenseBlog",
    url: "https://t.me/DefenseBlog",
    name: "Defense Blog",
    language: ["en"],
    region: ["UA", "RU", "GLOBAL"],
    bias: "ANALYST",
    tier: "SECONDARY",
    cluster: "WESTERN_ANALYTICS",
    credibilityScore: 70,
    firstMoverScore: 65,
    accuracyRate: 76,
    originalContentRate: 65,
    crossVerificationRate: 72,
    editorialLayerScore: 74,
    sourceProximityScore: 55,
    subscribers: 290000,
    avgPostsPerDay: 15,
    languages: ["en"],
    specialties: ["defense_procurement", "weapons_deliveries", "ukraine_aid", "military_analysis"],
    knownAffiliations: ["defenseblog.news — analytique défense — Ukraine-centré"],
    warningFlags: ["UKRAINE_FOCUS_BIAS"],
    medianLeadTimeMinutes: -15,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "thermopylaenews",
    handle: "thermopylaenews",
    url: "https://t.me/thermopylaenews",
    name: "Thermopylae News",
    language: ["en", "el"],
    region: ["GR", "TR", "ME", "GLOBAL"],
    bias: "ANALYST",
    tier: "SECONDARY",
    cluster: "NEUTRAL_AGGREGATOR",
    // Thermopylae = référence historique grecque — angle hellénique-nationaliste possible
    credibilityScore: 60,
    firstMoverScore: 58,
    accuracyRate: 65,
    originalContentRate: 55,
    crossVerificationRate: 60,
    editorialLayerScore: 62,
    sourceProximityScore: 55,
    subscribers: 110000,
    avgPostsPerDay: 18,
    languages: ["en", "el"],
    specialties: ["mediterranean_geopolitics", "turkey_greece", "middle_east", "naval_ops"],
    knownAffiliations: ["Perspective hellénique — possiblement nationaliste grec"],
    warningFlags: ["GREEK_NATIONALIST_LENS_POSSIBLE", "ANTI_TURKEY_FRAMING_POSSIBLE"],
    medianLeadTimeMinutes: -15,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "southerncrossintel",
    handle: "southerncrossintel",
    url: "https://t.me/southerncrossintel",
    name: "Southern Cross Intel",
    language: ["en"],
    region: ["AF", "GLOBAL"],
    bias: "ANALYST",
    tier: "SECONDARY",
    cluster: "WESTERN_ANALYTICS",
    credibilityScore: 65,
    firstMoverScore: 60,
    accuracyRate: 70,
    originalContentRate: 60,
    crossVerificationRate: 65,
    editorialLayerScore: 68,
    sourceProximityScore: 58,
    subscribers: 80000,
    avgPostsPerDay: 12,
    languages: ["en"],
    specialties: ["africa_conflicts", "sahel", "southern_hemisphere_geopolitics", "wagner_africa"],
    knownAffiliations: ["Analytique hémisphère sud — fort sur Afrique/Sahel"],
    warningFlags: [],
    medianLeadTimeMinutes: -20,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "infodefENGLAND",
    handle: "infodefENGLAND",
    url: "https://t.me/infodefENGLAND",
    name: "InfoDef England",
    language: ["en"],
    region: ["GLOBAL"],
    bias: "ANALYST",
    tier: "SECONDARY",
    cluster: "WESTERN_ANALYTICS",
    credibilityScore: 67,
    firstMoverScore: 62,
    accuracyRate: 72,
    originalContentRate: 55,
    crossVerificationRate: 68,
    editorialLayerScore: 70,
    sourceProximityScore: 52,
    subscribers: 140000,
    avgPostsPerDay: 14,
    languages: ["en"],
    specialties: ["uk_defense", "nato_ops", "ukraine_aid_uk", "defense_intel"],
    knownAffiliations: ["InfoDef — UK defense analytics"],
    warningFlags: ["UK_NATO_LENS"],
    medianLeadTimeMinutes: -10,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "CIG_telegram",
    handle: "CIG_telegram",
    url: "https://t.me/CIG_telegram",
    name: "CIG — Collective Intelligence Group",
    language: ["en"],
    region: ["GLOBAL"],
    bias: "ANALYST",
    tier: "SECONDARY",
    cluster: "WESTERN_ANALYTICS",
    credibilityScore: 66,
    firstMoverScore: 58,
    accuracyRate: 72,
    originalContentRate: 65,
    
    crossVerificationRate: 68,
    editorialLayerScore: 72,
    sourceProximityScore: 50,
    subscribers: 95000,
    avgPostsPerDay: 10,
    languages: ["en"],
    specialties: ["intelligence_analysis", "geopolitics", "threat_assessment", "osint"],
    knownAffiliations: ["Groupe d'intelligence collective — analytique"],
    warningFlags: [],
    medianLeadTimeMinutes: -5,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "militarywave",
    handle: "militarywave",
    url: "https://t.me/militarywave",
    name: "Military Wave",
    language: ["en"],
    region: ["GLOBAL"],
    bias: "AGGREGATOR",
    tier: "SECONDARY",
    cluster: "NEUTRAL_AGGREGATOR",
    credibilityScore: 62,
    firstMoverScore: 60,
    accuracyRate: 66,
    originalContentRate: 35,
    crossVerificationRate: 58,
    editorialLayerScore: 45,
    sourceProximityScore: 40,
    subscribers: 210000,
    avgPostsPerDay: 28,
    languages: ["en"],
    specialties: ["military_news", "defense", "conflict_aggregation"],
    knownAffiliations: ["Agrégateur militaire"],
    warningFlags: ["AGGREGATION_UNVERIFIED"],
    medianLeadTimeMinutes: -5,
    forwardedFrom: [],
    forwardedBy: [],
  },

  // ════════════════════════════════════════════════════════════
  // BLOC 5 — GÉOPOLITIQUE HISPANOPHONE
  // ════════════════════════════════════════════════════════════

  {
    id: "entre_guerras",
    handle: "entre_guerras",
    url: "https://t.me/entre_guerras",
    name: "Entre Guerras",
    language: ["es"],
    region: ["GLOBAL"],
    bias: "ANALYST",
    tier: "SECONDARY",
    cluster: "SPANISH_GEOPOLITICS",
    credibilityScore: 66,
    firstMoverScore: 55,
    accuracyRate: 70,
    originalContentRate: 65,
    crossVerificationRate: 65,
    editorialLayerScore: 72,
    sourceProximityScore: 48,
    subscribers: 95000,
    avgPostsPerDay: 12,
    languages: ["es"],
    specialties: ["geopolitica", "conflictos_armados", "latinoamerica", "medio_oriente"],
    knownAffiliations: ["Analyse géopolitique hispanophone — entre les guerres"],
    warningFlags: [],
    medianLeadTimeMinutes: 15,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "guerrasygeo",
    handle: "guerrasygeo",
    url: "https://t.me/guerrasygeo",
    name: "Guerras y Geopolítica",
    language: ["es"],
    region: ["GLOBAL"],
    bias: "ANALYST",
    tier: "SECONDARY",
    cluster: "SPANISH_GEOPOLITICS",
    credibilityScore: 65,
    firstMoverScore: 58,
    accuracyRate: 70,
    originalContentRate: 60,
    crossVerificationRate: 63,
    editorialLayerScore: 70,
    sourceProximityScore: 45,
    subscribers: 115000,
    avgPostsPerDay: 14,
    languages: ["es"],
    specialties: ["guerras_geopolitica", "medio_oriente_esp", "ucrania_esp", "africa"],
    knownAffiliations: ["Géopolitique hispanophone — neutre"],
    warningFlags: [],
    medianLeadTimeMinutes: 10,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "elOJOen",
    handle: "elOJOen",
    url: "https://t.me/elOJOen",
    name: "El OJO en",
    language: ["es"],
    region: ["GLOBAL"],
    bias: "ANALYST",
    tier: "SECONDARY",
    cluster: "SPANISH_GEOPOLITICS",
    credibilityScore: 63,
    firstMoverScore: 60,
    accuracyRate: 68,
    originalContentRate: 58,
    crossVerificationRate: 62,
    editorialLayerScore: 65,
    sourceProximityScore: 48,
    subscribers: 85000,
    avgPostsPerDay: 15,
    languages: ["es"],
    specialties: ["investigacion_geopolitica_esp", "conflictos", "inteligencia"],
    knownAffiliations: ["Investigation géopolitique hispanophone — 'l'œil'"],
    warningFlags: [],
    medianLeadTimeMinutes: 10,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "VenezuelaNetwork",
    handle: "VenezuelaNetwork",
    url: "https://t.me/VenezuelaNetwork",
    name: "Venezuela Network",
    language: ["es", "en"],
    region: ["VE", "LATAM", "RU"],
    bias: "AGGREGATOR",
    tier: "SECONDARY",
    cluster: "SPANISH_GEOPOLITICS",
    // Venezuela sous Maduro = aligné sur Russie/Iran — possible biais
    credibilityScore: 55,
    firstMoverScore: 58,
    accuracyRate: 62,
    originalContentRate: 50,
    crossVerificationRate: 52,
    editorialLayerScore: 52,
    sourceProximityScore: 60,
    subscribers: 145000,
    avgPostsPerDay: 20,
    languages: ["es", "en"],
    specialties: ["venezuela", "latam_geopolitics", "oil_energy", "russia_latam"],
    knownAffiliations: ["Réseau Venezuela — possible alignement régime Maduro"],
    warningFlags: ["PRO_VENEZUELA_BIAS_POSSIBLE", "CROSS_VERIFY_REGIME_CLAIMS"],
    medianLeadTimeMinutes: -10,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "GeneralMCNews",
    handle: "GeneralMCNews",
    url: "https://t.me/GeneralMCNews",
    name: "General MC News",
    language: ["en"],
    region: ["GLOBAL"],
    bias: "AGGREGATOR",
    tier: "TERTIARY",
    cluster: "NEUTRAL_AGGREGATOR",
    credibilityScore: 57,
    firstMoverScore: 55,
    accuracyRate: 62,
    originalContentRate: 25,
    crossVerificationRate: 52,
    editorialLayerScore: 38,
    sourceProximityScore: 28,
    subscribers: 130000,
    avgPostsPerDay: 40,
    languages: ["en"],
    specialties: ["global_news", "aggregation"],
    knownAffiliations: ["Agrégateur — identité inconnue"],
    warningFlags: ["IDENTITY_UNKNOWN", "HIGH_AGGREGATION"],
    medianLeadTimeMinutes: 5,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "geopolitics_prime",
    handle: "geopolitics_prime",
    url: "https://t.me/geopolitics_prime",
    name: "Geopolitics Prime",
    language: ["en"],
    region: ["GLOBAL"],
    bias: "ANALYST",
    tier: "SECONDARY",
    cluster: "NEUTRAL_AGGREGATOR",
    credibilityScore: 65,
    firstMoverScore: 52,
    accuracyRate: 70,
    originalContentRate: 60,
    crossVerificationRate: 65,
    editorialLayerScore: 70,
    sourceProximityScore: 45,
    subscribers: 180000,
    avgPostsPerDay: 10,
    languages: ["en"],
    specialties: ["geopolitics_analysis", "global_strategy", "multipolar_trends"],
    knownAffiliations: ["Analytique géopolitique — identité non-claire"],
    warningFlags: ["IDENTITY_UNCLEAR"],
    medianLeadTimeMinutes: 20,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "RiseGS",
    handle: "RiseGS",
    url: "https://t.me/RiseGS",
    name: "Rise Global Surveillance",
    language: ["en"],
    region: ["GLOBAL"],
    bias: "ANALYST",
    tier: "SECONDARY",
    cluster: "NEUTRAL_AGGREGATOR",
    credibilityScore: 55,
    firstMoverScore: 52,
    accuracyRate: 60,
    originalContentRate: 50,
    crossVerificationRate: 55,
    editorialLayerScore: 58,
    sourceProximityScore: 42,
    subscribers: 65000,
    avgPostsPerDay: 12,
    languages: ["en"],
    specialties: ["global_surveillance", "intelligence_gathering", "security"],
    knownAffiliations: ["Inconnu — surveillance globale"],
    warningFlags: ["LOW_FOLLOWER_COUNT", "IDENTITY_UNKNOWN"],
    medianLeadTimeMinutes: 0,
    forwardedFrom: [],
    forwardedBy: [],
  },

  // ════════════════════════════════════════════════════════════
  // BLOC 6 — DATA / DÉMOGRAPHIE / VISUALISATION
  // Canaux de données statistiques — utiles pour NEXUS MATRIX
  // ════════════════════════════════════════════════════════════

  {
    id: "dem0graphics",
    handle: "dem0graphics",
    url: "https://t.me/dem0graphics",
    name: "Demographics",
    language: ["en"],
    region: ["GLOBAL"],
    bias: "ANALYST",
    tier: "SECONDARY",
    cluster: "DATA_VISUALIZATION",
    extended_bias: "DATA_ANALYST",
    credibilityScore: 67,
    firstMoverScore: 40,
    accuracyRate: 72,
    originalContentRate: 70,
    crossVerificationRate: 65,
    editorialLayerScore: 65,
    sourceProximityScore: 45,
    subscribers: 220000,
    avgPostsPerDay: 8,
    languages: ["en"],
    specialties: ["population_data", "demographic_trends", "migration", "ethnic_composition"],
    knownAffiliations: ["Données démographiques — peut avoir agenda si sélection biaisée"],
    warningFlags: ["CHERRY_PICKING_DATA_RISK", "VERIFY_SOURCES_OF_DATA"],
    medianLeadTimeMinutes: 60,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "datadistribution",
    handle: "datadistribution",
    url: "https://t.me/datadistribution",
    name: "Data Distribution",
    language: ["en"],
    region: ["GLOBAL"],
    bias: "ANALYST",
    tier: "SECONDARY",
    cluster: "DATA_VISUALIZATION",
    extended_bias: "DATA_ANALYST",
    credibilityScore: 64,
    firstMoverScore: 35,
    accuracyRate: 70,
    originalContentRate: 65,
    crossVerificationRate: 62,
    editorialLayerScore: 62,
    sourceProximityScore: 40,
    subscribers: 155000,
    avgPostsPerDay: 6,
    languages: ["en"],
    specialties: ["statistical_data", "geospatial_data", "conflict_statistics"],
    knownAffiliations: ["Partage de données statistiques"],
    warningFlags: ["DATA_SELECTION_BIAS_POSSIBLE"],
    medianLeadTimeMinutes: 120,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "TruthGraphs",
    handle: "TruthGraphs",
    url: "https://t.me/TruthGraphs",
    name: "Truth Graphs",
    language: ["en"],
    region: ["GLOBAL"],
    bias: "ANALYST",
    tier: "SECONDARY",
    cluster: "DATA_VISUALIZATION",
    extended_bias: "DATA_ANALYST",
    // NOTE: "Truth" dans le nom = signal d'alerte potentiel (souvent alt-media)
    credibilityScore: 58,
    firstMoverScore: 35,
    accuracyRate: 65,
    originalContentRate: 68,
    crossVerificationRate: 58,
    editorialLayerScore: 58,
    sourceProximityScore: 38,
    subscribers: 140000,
    avgPostsPerDay: 7,
    languages: ["en"],
    specialties: ["data_visualization", "infographics", "statistics"],
    knownAffiliations: ["Visualisation données — 'Truth' dans nom = prudence"],
    warningFlags: ["TRUTH_BRANDING_WARNING", "VERIFY_DATA_SOURCES", "CHERRY_PICKING_RISK"],
    medianLeadTimeMinutes: 120,
    forwardedFrom: [],
    forwardedBy: [],
  },

  // ════════════════════════════════════════════════════════════
  // BLOC 7 — EXTRÊME-DROITE / CONSPIRATIONNISTE
  // ⚠️ AVERTISSEMENT : Ces canaux sont inclus UNIQUEMENT pour
  // cartographier leur influence sur l'espace informationnel.
  // NEXUS les pénalise lourdement et les isole dans l'analyse.
  // Ils NE SONT PAS des sources de confiance.
  // ════════════════════════════════════════════════════════════

  {
    id: "thuletide",
    handle: "thuletide",
    url: "https://t.me/thuletide",
    name: "Thuletide",
    language: ["en"],
    region: ["GLOBAL"],
    bias: "AGGREGATOR",
    tier: "TERTIARY",
    cluster: "FAR_RIGHT_EXTREMIST",
    extended_bias: "FAR_RIGHT",
    // THULE = référence directe à la Société Thulé — organisation ésotérique nazie
    //         qui a précédé et préparé idéologiquement le NSDAP
    // Score minimal — inclus pour traçage de narratives extrémistes uniquement
    credibilityScore: 15,
    firstMoverScore: 30,
    accuracyRate: 20,
    originalContentRate: 60,
    crossVerificationRate: 10,
    editorialLayerScore: 40,
    sourceProximityScore: 15,
    subscribers: 85000,
    avgPostsPerDay: 8,
    languages: ["en"],
    specialties: ["white_nationalism", "great_replacement_theory", "antisemitism", "neo_nazi_ideology"],
    knownAffiliations: ["Nationalisme blanc extrémiste — référence Thulé Gesellschaft nazie"],
    warningFlags: [
      "EXTREMIST_CONTENT",
      "FAR_RIGHT_CONFIRMED",
      "ANTISEMITIC_CONTENT",
      "DISINFO_AMPLIFICATION",
      "DO_NOT_CITE_AS_SOURCE",
      "MONITOR_FOR_NARRATIVE_INFILTRATION_ONLY",
    ],
    medianLeadTimeMinutes: 180, // Jamais premier — recyclage de narratives
    forwardedFrom: [],
    forwardedBy: ["European_dissident"],
  },

  {
    id: "PrivSecGoy",
    handle: "PrivSecGoy",
    url: "https://t.me/PrivSecGoy",
    name: "PrivSec Goy",
    language: ["en"],
    region: ["GLOBAL"],
    bias: "AGGREGATOR",
    tier: "TERTIARY",
    cluster: "FAR_RIGHT_EXTREMIST",
    extended_bias: "FAR_RIGHT",
    // "Goy" utilisé ici comme terme dépréciatif antisémite (≠ usage religieux neutre)
    // Contexte du canal = contenu antisémite documenté
    credibilityScore: 12,
    firstMoverScore: 20,
    accuracyRate: 18,
    originalContentRate: 55,
    crossVerificationRate: 5,
    editorialLayerScore: 30,
    sourceProximityScore: 10,
    subscribers: 45000,
    avgPostsPerDay: 10,
    languages: ["en"],
    specialties: ["antisemitic_conspiracy", "privacy_ops_pretext", "jewish_conspiracy_theories"],
    knownAffiliations: ["Contenu antisémite — 'Goy' utilisé comme terme dépréciatif"],
    warningFlags: [
      "ANTISEMITIC_CONTENT_CONFIRMED",
      "EXTREMIST_CONTENT",
      "CONSPIRACY_ANTISEMITE",
      "DO_NOT_CITE_AS_SOURCE",
      "MONITOR_FOR_NARRATIVE_DRIFT_ONLY",
    ],
    medianLeadTimeMinutes: 300,
    forwardedFrom: ["thuletide"],
    forwardedBy: [],
  },

  {
    id: "European_dissident",
    handle: "European_dissident",
    url: "https://t.me/European_dissident",
    name: "European Dissident",
    language: ["en"],
    region: ["EU"],
    bias: "AGGREGATOR",
    tier: "TERTIARY",
    cluster: "FAR_RIGHT_EXTREMIST",
    extended_bias: "FAR_RIGHT",
    // Nationalisme européen d'extrême-droite — amplifie Slavyangrad (pro-Russie)
    credibilityScore: 30,
    firstMoverScore: 35,
    accuracyRate: 35,
    originalContentRate: 50,
    crossVerificationRate: 20,
    editorialLayerScore: 45,
    sourceProximityScore: 25,
    subscribers: 120000,
    avgPostsPerDay: 15,
    languages: ["en"],
    specialties: ["european_nationalism", "anti_eu", "anti_immigration", "russia_sympathizer"],
    knownAffiliations: ["Nationalisme européen extrême-droite — amplifie narratives pro-russes"],
    warningFlags: [
      "FAR_RIGHT_CONFIRMED",
      "PRO_RUSSIA_AMPLIFICATION",
      "ANTI_EU_NATIONALIST",
      "EXTREMIST_CONTENT",
    ],
    medianLeadTimeMinutes: 120,
    forwardedFrom: ["Slavyangrad", "thuletide"],
    forwardedBy: ["thuletide"],
  },

  {
    id: "TheConspiracyHole",
    handle: "TheConspiracyHole",
    url: "https://t.me/TheConspiracyHole",
    name: "The Conspiracy Hole",
    language: ["en"],
    region: ["GLOBAL"],
    bias: "AGGREGATOR",
    tier: "TERTIARY",
    cluster: "CONSPIRACY_ALT",
    extended_bias: "CONSPIRACY",
    credibilityScore: 25,
    firstMoverScore: 40,
    accuracyRate: 28,
    originalContentRate: 45,
    crossVerificationRate: 15,
    editorialLayerScore: 35,
    sourceProximityScore: 15,
    subscribers: 95000,
    avgPostsPerDay: 20,
    languages: ["en"],
    specialties: ["conspiracy_theories", "deep_state", "nwo_narratives", "anti_establishment"],
    knownAffiliations: ["Conspirationniste — mélange de vraies infos et théories non-vérifiées"],
    warningFlags: [
      "CONSPIRACY_HIGH_MISINFO",
      "DO_NOT_CITE",
      "MONITOR_FOR_VIRAL_NARRATIVES_ONLY",
    ],
    medianLeadTimeMinutes: 240,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "Revelations_and_Rabbit_Holes",
    handle: "Revelations_and_Rabbit_Holes",
    url: "https://t.me/Revelations_and_Rabbit_Holes",
    name: "Revelations & Rabbit Holes",
    language: ["en"],
    region: ["GLOBAL"],
    bias: "AGGREGATOR",
    tier: "TERTIARY",
    cluster: "CONSPIRACY_ALT",
    extended_bias: "CONSPIRACY",
    credibilityScore: 22,
    firstMoverScore: 38,
    accuracyRate: 25,
    originalContentRate: 48,
    crossVerificationRate: 12,
    editorialLayerScore: 32,
    sourceProximityScore: 12,
    subscribers: 75000,
    avgPostsPerDay: 18,
    languages: ["en"],
    specialties: ["esoteric_conspiracy", "secret_societies", "globalist_narratives"],
    knownAffiliations: ["Conspirationniste ésotérique"],
    warningFlags: [
      "CONSPIRACY_HIGH_MISINFO",
      "DO_NOT_CITE",
      "MONITOR_VIRAL_SPREAD_ONLY",
    ],
    medianLeadTimeMinutes: 300,
    forwardedFrom: ["TheConspiracyHole"],
    forwardedBy: [],
  },

  {
    id: "navigatingthelies",
    handle: "navigatingthelies",
    url: "https://t.me/navigatingthelies",
    name: "Navigating the Lies",
    language: ["en"],
    region: ["GLOBAL"],
    bias: "AGGREGATOR",
    tier: "TERTIARY",
    cluster: "CONSPIRACY_ALT",
    extended_bias: "CONSPIRACY",
    credibilityScore: 35,
    firstMoverScore: 42,
    accuracyRate: 38,
    originalContentRate: 50,
    crossVerificationRate: 22,
    editorialLayerScore: 42,
    sourceProximityScore: 20,
    subscribers: 65000,
    avgPostsPerDay: 15,
    languages: ["en"],
    specialties: ["mainstream_media_criticism", "alternative_narratives", "fact_checking_skepticism"],
    knownAffiliations: ["Alt-media — critique des médias mainstream avec agenda conspirationniste"],
    warningFlags: [
      "CONSPIRACY_ADJACENT",
      "ANTI_MAINSTREAM_MEDIA_BIAS",
      "MIXED_CONTENT_QUALITY",
    ],
    medianLeadTimeMinutes: 180,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "mediatricks",
    handle: "mediatricks",
    url: "https://t.me/mediatricks",
    name: "Media Tricks",
    language: ["en"],
    region: ["GLOBAL"],
    bias: "AGGREGATOR",
    tier: "TERTIARY",
    cluster: "CONSPIRACY_ALT",
    extended_bias: "CONSPIRACY",
    credibilityScore: 40,
    firstMoverScore: 45,
    accuracyRate: 45,
    originalContentRate: 58,
    crossVerificationRate: 30,
    editorialLayerScore: 50,
    sourceProximityScore: 25,
    subscribers: 85000,
    avgPostsPerDay: 12,
    languages: ["en"],
    specialties: ["media_manipulation", "propaganda_analysis", "deepfake_detection_skeptical"],
    knownAffiliations: ["Critique médias mainstream — parfois légitime, souvent conspirationniste"],
    warningFlags: ["CONSPIRACY_ADJACENT", "MEDIA_CRITICISM_BIAS"],
    medianLeadTimeMinutes: 120,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "Reality_Theories",
    handle: "Reality_Theories",
    url: "https://t.me/Reality_Theories",
    name: "Reality Theories",
    language: ["en"],
    region: ["GLOBAL"],
    bias: "AGGREGATOR",
    tier: "TERTIARY",
    cluster: "CONSPIRACY_ALT",
    extended_bias: "CONSPIRACY",
    credibilityScore: 28,
    firstMoverScore: 35,
    accuracyRate: 30,
    originalContentRate: 50,
    crossVerificationRate: 15,
    editorialLayerScore: 38,
    sourceProximityScore: 15,
    subscribers: 55000,
    avgPostsPerDay: 14,
    languages: ["en"],
    specialties: ["reality_questioning", "deep_state", "alternative_history"],
    knownAffiliations: ["Conspirationniste — questionnement réalité"],
    warningFlags: ["CONSPIRACY_HIGH_MISINFO", "DO_NOT_CITE"],
    medianLeadTimeMinutes: 300,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "myLordBebo",
    handle: "myLordBebo",
    url: "https://t.me/myLordBebo",
    name: "MyLordBebo",
    language: ["en"],
    region: ["GLOBAL"],
    bias: "AGGREGATOR",
    tier: "TERTIARY",
    cluster: "CONSPIRACY_ALT",
    extended_bias: "CONSPIRACY",
    // Large audience — amplifie des théories conspirationnistes avec contenu de guerre mélangé
    credibilityScore: 38,
    firstMoverScore: 48,
    accuracyRate: 42,
    originalContentRate: 55,
    crossVerificationRate: 25,
    editorialLayerScore: 45,
    sourceProximityScore: 20,
    subscribers: 420000,
    avgPostsPerDay: 20,
    languages: ["en"],
    specialties: ["war_news_mixed", "conspiracy_alt_media", "anti_establishment"],
    knownAffiliations: ["Alt-media grande audience — mélange news réelles et conspirations"],
    warningFlags: [
      "CONSPIRACY_ADJACENT",
      "HIGH_AUDIENCE_HIGH_RISK",
      "MIXED_QUALITY_CONTENT",
      "DO_NOT_CITE_AS_PRIMARY",
    ],
    medianLeadTimeMinutes: 60,
    forwardedFrom: ["TheConspiracyHole", "disclosetv"],
    forwardedBy: [],
  },

  // ════════════════════════════════════════════════════════════
  // BLOC 8 — CANAUX DIVERS
  // ════════════════════════════════════════════════════════════

  {
    id: "wofnon",
    handle: "wofnon",
    url: "https://t.me/wofnon",
    name: "WOFNON",
    language: ["en"],
    region: ["GLOBAL"],
    bias: "AGGREGATOR",
    tier: "TERTIARY",
    cluster: "NEUTRAL_AGGREGATOR",
    credibilityScore: 48,
    firstMoverScore: 50,
    accuracyRate: 52,
    originalContentRate: 30,
    crossVerificationRate: 42,
    editorialLayerScore: 35,
    sourceProximityScore: 25,
    subscribers: 55000,
    avgPostsPerDay: 20,
    languages: ["en"],
    specialties: ["conflict_aggregation"],
    knownAffiliations: ["Inconnu — agrégateur"],
    warningFlags: ["IDENTITY_UNKNOWN", "LOW_VERIFICATION"],
    medianLeadTimeMinutes: 15,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "ophiucu",
    handle: "ophiucu",
    url: "https://t.me/ophiucu",
    name: "Ophiucu",
    language: ["en"],
    region: ["GLOBAL"],
    bias: "ANALYST",
    tier: "SECONDARY",
    cluster: "NEUTRAL_AGGREGATOR",
    // Ophiuchus = constellation — signifie peut-être intelligence/observation globale
    credibilityScore: 52,
    firstMoverScore: 52,
    accuracyRate: 58,
    originalContentRate: 55,
    crossVerificationRate: 50,
    editorialLayerScore: 55,
    sourceProximityScore: 38,
    subscribers: 45000,
    avgPostsPerDay: 12,
    languages: ["en"],
    specialties: ["geopolitics", "intelligence"],
    knownAffiliations: ["Inconnu — analytique"],
    warningFlags: ["IDENTITY_UNKNOWN", "LOW_VERIFICATION_TRACK_RECORD"],
    medianLeadTimeMinutes: 20,
    forwardedFrom: [],
    forwardedBy: [],
  },

  {
    id: "liusivaya",
    handle: "liusivaya",
    url: "https://t.me/liusivaya",
    name: "Liu Sivaya",
    language: ["ru", "en"],
    region: ["UA", "RU"],
    bias: "PRO_RUSSIA",
    tier: "TERTIARY",
    cluster: "RUSSIAN_PROPAGANDA",
    credibilityScore: 42,
    firstMoverScore: 48,
    accuracyRate: 48,
    originalContentRate: 55,
    crossVerificationRate: 35,
    editorialLayerScore: 45,
    sourceProximityScore: 52,
    subscribers: 35000,
    avgPostsPerDay: 18,
    languages: ["ru", "en"],
    specialties: ["ukraine_war_russia_pov", "frontline_russia"],
    knownAffiliations: ["Perspective pro-Russie sur Ukraine"],
    warningFlags: ["PRO_RUSSIA_LENS", "VERIFY_ALL_FRONTLINE_CLAIMS"],
    medianLeadTimeMinutes: -20,
    forwardedFrom: ["Slavyangrad"],
    forwardedBy: [],
  },

];

// ─── GRAPHE D'OPPOSITIONS NARRATIVES ─────────────────────────
// Basé sur: analyse éditoriale, cross-posting, fact-checking mutuel

export const NARRATIVE_OPPOSITIONS: ChannelOpposition[] = [

  // Opposition directe pro-Israël vs pro-Résistance
  {
    channelA: "allisrael",
    channelB: "FotrosResistancee",
    type: "DIRECT_NARRATIVE_OPPOSITION",
    intensity: 95,
    notes: "Récits radicalement opposés sur Gaza, Liban, Iran — même événement, lecture inverse",
  },
  {
    channelA: "idfofficial",
    channelB: "presstv",
    type: "DIRECT_NARRATIVE_OPPOSITION",
    intensity: 98,
    notes: "Communiqués officiels IDF vs narratives État iranien — opposition systématique",
  },
  {
    channelA: "JewsIsrael",
    channelB: "QudsNen",
    type: "IDEOLOGICAL_OPPOSITION",
    intensity: 90,
    notes: "Judéité pro-Israël vs résistance pro-Hamas — même terrain, lectures opposées",
  },
  {
    channelA: "DocumentingIsrael",
    channelB: "idostandwithisrael",
    type: "IDEOLOGICAL_OPPOSITION",
    intensity: 75,
    notes: "Documentation critique IDF vs soutien inconditionnel — deux registres différents",
  },

  // Opposition pro-Ukraine (ISW) vs pro-Russie
  {
    channelA: "iswnews_en",
    channelB: "Slavyangrad",
    type: "DIRECT_NARRATIVE_OPPOSITION",
    intensity: 92,
    notes: "ISW rigoreux pro-Ukraine vs Slavyangrad propagande pro-Russie — narratives militaires opposés systématiquement",
  },
  {
    channelA: "iswnews_en",
    channelB: "FiorellaInMoscow",
    type: "DIRECT_NARRATIVE_OPPOSITION",
    intensity: 88,
    notes: "ISW analytique vs correspondante pro-Kremlin depuis Moscou",
  },
  {
    channelA: "iswnews_en",
    channelB: "sonar_21",
    type: "FACTUAL_CONTRADICTION",
    intensity: 85,
    notes: "Bilans des pertes, avances territoriales: chiffres systématiquement contradictoires",
  },
  {
    channelA: "DefenseBlog",
    channelB: "tass_es",
    type: "FACTUAL_CONTRADICTION",
    intensity: 80,
    notes: "Livraisons d'armes à Ukraine vs narratives TASS : faits bruts divergents",
  },

  // Opposition Western vs Résistance sur Liban/Hezbollah
  {
    channelA: "LebUpdate",
    channelB: "Marwa_OsmanLB",
    type: "IDEOLOGICAL_OPPOSITION",
    intensity: 70,
    notes: "Journalisme libanais neutre vs commentateur pro-Hezbollah — même espace géographique, lecture différente",
  },

  // Opposition far-right vs pro-Israël
  {
    channelA: "thuletide",
    channelB: "JewsIsrael",
    type: "IDEOLOGICAL_OPPOSITION",
    intensity: 99,
    notes: "AVERTISSEMENT: Extrémisme antisémite vs communauté juive — opposition totale",
  },
  {
    channelA: "PrivSecGoy",
    channelB: "JewishNews24",
    type: "IDEOLOGICAL_OPPOSITION",
    intensity: 99,
    notes: "AVERTISSEMENT: Contenu antisémite documenté vs presse juive — opposition totale",
  },

  // Opposition ISW vs conspirationnistes
  {
    channelA: "iswnews_en",
    channelB: "TheConspiracyHole",
    type: "FACTUAL_CONTRADICTION",
    intensity: 80,
    notes: "Analyse factuelle vs théories conspirationnistes sur les mêmes événements militaires",
  },

  // Clash geopolitics
  {
    channelA: "ClashReport",
    channelB: "tass_es",
    type: "FACTUAL_CONTRADICTION",
    intensity: 65,
    notes: "Agrégateur neutre vs narratives TASS — vérifiable sur mêmes événements",
  },
];

// ─── ALLIANCES / CLUSTERS D'AMPLIFICATION ────────────────────
// Cross-posting documenté ou présumé — propagation de narratives

export const NARRATIVE_ALLIANCES: ChannelAlliance[] = [
  {
    channels: ["Slavyangrad", "FiorellaInMoscow", "tass_es", "sonar_21", "Irinamar_Z", "liusivaya", "VanessaBeeley"],
    cluster: "RUSSIAN_PROPAGANDA",
    amplificationRate: 68,
    notes: "Réseau propagande russe documenté. Slavyangrad → FiorellaInMoscow → Taylor Hudak → canaux américains pro-Trump. Source: OpenMinds Ltd 2024, OSINT for Ukraine 2025.",
  },
  {
    channels: ["FotrosResistancee", "QudsNen", "Resistancetoast", "presstv", "Marwa_OsmanLB"],
    cluster: "RESISTANCE_AXIS",
    amplificationRate: 72,
    notes: "Axe de Résistance iranien — IRGC, Hezbollah, Hamas. Cross-posting massif. Proximité opérationnelle forte.",
  },
  {
    channels: ["JewsIsrael", "allisrael", "JewishNews24", "Israel_Realtime_Digest", "idostandwithisrael", "JewishBreakingNewsTelegram"],
    cluster: "ISRAEL_PRO",
    amplificationRate: 60,
    notes: "Cluster pro-Israël — principalement agrégateurs et canaux communautaires. Source partagée: idfofficial.",
  },
  {
    channels: ["thuletide", "European_dissident", "PrivSecGoy"],
    cluster: "FAR_RIGHT_EXTREMIST",
    amplificationRate: 65,
    notes: "AVERTISSEMENT: Réseau extrémiste droite radicale. Amplifie narratives pro-russes (Slavyangrad). GNET Research 2025: algorithme Telegram crée pathways entre extrémismes.",
  },
  {
    channels: ["TheConspiracyHole", "Revelations_and_Rabbit_Holes", "navigatingthelies", "myLordBebo", "mediatricks", "disclosetv", "Reality_Theories"],
    cluster: "CONSPIRACY_ALT",
    amplificationRate: 55,
    notes: "Réseau alt-media conspirationniste. Mélange parfois avec narratives pro-russes ou pro-Iran.",
  },
  {
    channels: ["iswnews_en", "ClashReport", "MilitantWire", "armapedia", "DefenseBlog"],
    cluster: "WESTERN_ANALYTICS",
    amplificationRate: 45,
    notes: "Analytiques occidentaux — meilleure qualité du batch. ISW comme source principale d'analyse.",
  },
  {
    channels: ["dem0graphics", "datadistribution", "TruthGraphs"],
    cluster: "DATA_VISUALIZATION",
    amplificationRate: 38,
    notes: "Données statistiques — vérifier sélection des données (cherry-picking possible).",
  },
  {
    channels: ["entre_guerras", "guerrasygeo", "elOJOen", "VenezuelaNetwork"],
    cluster: "SPANISH_GEOPOLITICS",
    amplificationRate: 42,
    notes: "Géopolitique hispanophone — angle LatAm utile pour NEXUS sur opérations régionales.",
  },
];

// ─── MATRICE D'OPPOSITION RAPIDE ─────────────────────────────
// Pour le composant NexusPanel → onglet MATRIX

export const OPPOSITION_MATRIX: Record<string, string[]> = {
  // Ces canaux se contredisent systématiquement
  iswnews_en:        ["Slavyangrad", "FiorellaInMoscow", "sonar_21", "tass_es", "Irinamar_Z"],
  idfofficial:       ["presstv", "FotrosResistancee", "QudsNen", "Marwa_OsmanLB"],
  JewsIsrael:        ["QudsNen", "FotrosResistancee", "Resistancetoast", "AlHaqNews"],
  ClashReport:       ["tass_es", "FiorellaInMoscow"],
  allisrael:         ["FotrosResistancee", "presstv", "QudsNen"],
  DefenseBlog:       ["tass_es", "sonar_21"],
  // Opposition absolue extrémiste
  JewishNews24:      ["thuletide", "PrivSecGoy"],
};

// ─── EXPORT COMBINÉ POUR INTEGRATION telegram-intel.ts ────────

export const ALL_V4_CHANNEL_IDS = NEXUS_CHANNELS_V4.map(c => c.id);

export const V4_CLUSTER_SUMMARY = {
  RESISTANCE_AXIS:    NEXUS_CHANNELS_V4.filter(c => c.cluster === "RESISTANCE_AXIS").length,
  ISRAEL_PRO:         NEXUS_CHANNELS_V4.filter(c => c.cluster === "ISRAEL_PRO").length,
  RUSSIAN_PROPAGANDA: NEXUS_CHANNELS_V4.filter(c => c.cluster === "RUSSIAN_PROPAGANDA").length,
  WESTERN_ANALYTICS:  NEXUS_CHANNELS_V4.filter(c => c.cluster === "WESTERN_ANALYTICS").length,
  FAR_RIGHT_EXTREMIST:NEXUS_CHANNELS_V4.filter(c => c.cluster === "FAR_RIGHT_EXTREMIST").length,
  CONSPIRACY_ALT:     NEXUS_CHANNELS_V4.filter(c => c.cluster === "CONSPIRACY_ALT").length,
  DATA_VISUALIZATION: NEXUS_CHANNELS_V4.filter(c => c.cluster === "DATA_VISUALIZATION").length,
  SPANISH_GEOPOLITICS:NEXUS_CHANNELS_V4.filter(c => c.cluster === "SPANISH_GEOPOLITICS").length,
  NEUTRAL_AGGREGATOR: NEXUS_CHANNELS_V4.filter(c => c.cluster === "NEUTRAL_AGGREGATOR").length,
};
